### ISSUE TITLE
Replace dist dir with single js file

### ISSUE THREAD

**Issue by cjlarose** [cjlarose/weiqi.js#20]
Or two, one minified. For folks not using browserify

**Comment by cjlarose** [comment]
http://www.mattburkedev.com/export-a-global-to-the-window-object-with-browserify/

Seems like a good pattern

**Comment by rchasman** [comment]
This is straight cheating dawg

**Comment by cjlarose** [comment]
Node.JS users won't have anything thrown into their global namespace. But for people that want to get up and running quickly with weiqi.js, they can just pull down the already-built file and get to work. That way they don't have to write a gruntfile/gulpfile/makefile and all that shit. There are still people out there without build systems for their JS!
