### ISSUE TITLE
areaScore returns 25 after one stone in upper-left corner. Bug?

### ISSUE THREAD

**Issue by gamecubate** [cjlarose/weiqi.js#27]
Testing weiqi.js with a 5x5 board, after adding one black stone at 0,0, game.areaScore() returns 25, which seems strange -- from the little I know about Go. Is this a bug?

**Comment by nikolaswise** [comment]
@gamecubate I don't believe this is a bug. With only a single stone on the board, it's implied that the entire board belongs to black. Scoring is only estimatable until the endgame.

**Comment by gamecubate** [comment]
Thanks @nikolaswise. That makes perfect sense.
