### ISSUE TITLE
Will this support and computer fight? 

### ISSUE THREAD

**Issue by FENGYINYUANYOU** [cjlarose/weiqi.js#31]
Will this support and computer fight? thank you

**Comment by grummbunger** [comment]
this is an external object of a go board, that one sends a play and then is returned a string of what the board looks like now, along with history of plays. as an implementer of the weiqi.js found here one needs then to write code to play the game, that code programmed not to play illegal plays or to handle the catch. i have created an AI to play with this board and have found that it works exactly correct and it only really lacks an undo command. if one wants to see the board in play so they can confirm if the board works before programming it as a dependency to their app. check out the board in play at 
gomango.ddns.net
 as i use the weiqi.js globally installed to npm on my server with four play boards, (remember to define external objects with different names) ps i recomend installing it as non global but... lol to late for me.

**Comment by cjlarose** [comment]
Thanks @grummbunger !
