### ISSUE TITLE
TypeError: Weiqi.createGame is not a function

### ISSUE THREAD

**Issue by grummbunger** [cjlarose/weiqi.js#32]
firstly thanks for putting effort into free code, i understand the hard work.

i did the folowing:
(console)
npm install -g weiqi

i added to index.js 

var Weiqi = require('weiqi');
console.log(Weiqi);
var game = Weiqi.createGame(9);

the console.log reports the functions
i have looked at the code,
i have localpathed any ref in package.json
i have installed not -g and directly pathed to the weiqi dir with immutable all pathed in pack.json (after trying defaults) i have tried other functions pass etc.)
i am hoping to get my chat bot to play a game of go, even just random moves... this is in a working file with a tem mainclock just to get familier with the weiqi library.

i get error saying 

game = Weiqi.createGame(9);
                          ^
TypeError ... is npt a function....

"they" say cillic error of requires but since i only require one thing....

**Comment by cjlarose** [comment]
Thanks so much for your bug report. I was able to reproduce the issue you're describing.

```js
// index.js
var Weiqi = require('weiqi');
console.log(Weiqi);
var game = Weiqi.createGame(9);
```

```js
~/dev/weiqi-test $ node index.js
{
  default: {
    createGame: [Function: createGame],
    isOver: [Function: isOver],
    play: [Function: play],
    pass: [Function: pass],
    areaScore: [Function: areaScore]
  }
}
/Users/chris.larose/dev/weiqi-test/index.js:3
var game = Weiqi.createGame(9);
                 ^

TypeError: Weiqi.createGame is not a function
    at Object.<anonymous> (/Users/chris.larose/dev/weiqi-test/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:1
2)
    at internal/main/run_main_module.js:18:47
```

I'm using node `v12.16.1`. What version of Node are you using?

**Comment by cjlarose** [comment]
I think the problem is related to how the library uses ECMAScript modules to export its declarations, but the documentation in the README imports the library using CommonJS. I'll need some time to figure out the best way to fix this, but for now, you can add `.default` to your `require` as a workaround.

```js
var Weiqi = require('weiqi').default;

console.log(Weiqi);
var game = Weiqi.createGame(9);
console.log(game.get('currentPlayer'));
console.log(Weiqi.isOver(game));
```

**Comment by grummbunger** [comment]
Node 8.x wow 12 is out. Cool. I'll be looking into trying I did a wack of
tries last night.

Your code is very clean so easy to check out stuff. I have the zip as well.

Thanks much!

**Comment by grummbunger** [comment]
Cool I'll try the .default!

**Comment by grummbunger** [comment]
the .default worked like a big charm, now i get the game board MAP  and
history MAP!
ill be able to use my parser routines to 'see' the board. i will definately
credit and link your github.

cheers from Ron Michel

**Comment by grummbunger** [comment]
super cool, got game parsed, i can now, without throwing exception have the computer place a stone next to a stone i place after checking if it can place there. i have an ascii representation of the board made from a long string of plus signs... all worked into my chatbot. very cool this weiqi.js.
