### ISSUE TITLE
double turn and with allowance of suicide

### ISSUE THREAD

**Issue by grummbunger** [cjlarose/weiqi.js#33]
my ai before taking a turn asks for who is current color then makes a move for the current color. the move generated is for a var the game knows is next color, and is rare cases the last played stone say was white so my ai know it is black but somehow the board thinks it is white still to move and allows white to place where black should thus some times this is a suicide. the catch is not thrown the stone suicides and is accepted as play.
the last part (the board allows the removal of the suicide stone) this happens on a crowded board, so far i can not isolate a situation and i will do a workaround detect for it. 

one such game this happens is http://eidogo.com/#477XD619y
late in the game are a lot of these up to 5 times black got turns in a row. 

like i say i ask the board for current color, the prev stone was placed proper yet the color did not increment, and i can tell the ai thinks in proper color by its placement to kill a stone.
not hard to workaround but you might want to know someting is up.

if i get the answer ill let you know,

ps hey what you think of that game tho, that was generated on your board! still not machine learning that is purely scripted go playing.

**Comment by grummbunger** [comment]
just going to close this one

**Comment by cjlarose** [comment]
Thanks for the bug report and it's super cool anytime to see the project being used in action!

If you don't mind, I'll reopen the issue just so it's clear that there's still an active issue.

**Comment by cjlarose** [comment]
Oh I get it. Reopened in  #34

**Comment by grummbunger** [comment]
ty cjlarose, i got an easy workaround, i posted, again sorry for the double post.
